### ISSUE TITLE
OkieTalkie sample App 실행시 계속 disconnected됬다고 떠요

### ISSUE THREAD

**Issue by quki** [mysticPrg/Gear2Net#3]
**OkieTalkie** sample App 실행 시
안드로이드 쪽 service 어플인 브릿지앱을 깔았음에도 연결이 안되는지
OkieTalkie 첫화면에서 **Not connected**라고 뜨고 실행이 안되네요.

**Comment by mysticPrg** [comment]
현재 기어2 장비를 가지고 있지 않아서 정확한 확인은 불가능합니다.
지금 당장 생각나는 예상 원인은 두 가지입니다.
1) OkieTalkie 서버 설정 (오키토키 앱은 NodeJS로 작성된 서버가 있어야 동작합니다) 
2) 기어2 펌웨어 업데이트로 인한 변경점
꽤 오랫동안 관리하지 않은 프로젝트라서 부끄럽네요...
진행하시는 프로젝트나 기어2넷 관련 궁금한 점 있으시면 언제든 메일 주세요 :)
감사합니다.

**Comment by quki** [comment]
앗 그렇군요! 
좋은 오픈 라이브러리인거 같아서 한번 실행해보려 했는데 아쉽네요 ^^

혹시  OkieTalkie 서버 설정이라는 것이 
제 컴퓨터에 NodeJS 서버가 설치되어있어야 한다는 말씀이신가요?

**Comment by mysticPrg** [comment]
네 Sample 폴더에 보시면 OkieTalkieServer 라는 폴더가 있을거에요.
오키토키 앱은 [내 기어2] <-> [내 스마트폰] <-> [오키토키서버] <-> [상대스마트폰] <-> [상대 기어2]
이렇게 음성 데이터를 전달하기 때문에 서버가 필요합니다.
실사용에 목적이 있는게 아니라 이런식으로 UDP 소켓을 활용할 수 있다는 걸
보여주려는 의도로 만들었으니 참고 바랍니다.

**Comment by quki** [comment]
아하 그렇군요 
잘알겠습니다 ^^
